// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Microsoft.Build;

internal enum ErrorCode
{
    /*
     * The Build message bucket is: MSB4000 - MSB4999
     *
     * Next message code should be MSB4281
     *
     * Don't forget to update this comment after using a new code.
     */
    LoggerNotFoundError = 1020,
    LoggerCreationError = 1021,
    AmbiguousTaskParameterError = 4001,
    AttributeTypeLoadError = 4002,
    BadlyCasedSpecialTaskAttribute = 4003,
    CannotModifyReservedProperty = 4004,
    CircularDependency = 4006,
    CircularDependencyInTargetGraph = 4006,
    DefaultTasksFileFailure = 4009,
    DefaultTasksFileLoadFailureWarning = 4010,
    DuplicateImport = 4011,
    EmbeddedItemVectorCannotBeItemized = 4012,
    FatalBuildError = 4014,
    FatalErrorDuringLoggerShutdown = 4015,
    FatalErrorWhileInitializingLogger = 4016,
    FatalErrorWhileLogging = 4017,
    FatalErrorWhileLoggingWithInnerException = 4017,
    FatalTaskError = 4018,
    ImportedProjectNotFound = 4019,
    InvalidAttributeValue = 4020,
    InvalidContinueOnErrorAttribute = 4021,
    InvalidEvaluatedAttributeValue = 4022,
    CannotEvaluateItemMetadata = 4023,
    InvalidImportedProjectFile = 4024,
    InvalidProjectFile = 4025,
    InvalidTaskAttributeError = 4026,
    InvalidTaskItemsInTaskOutputs = 4027,
    FailedToRetrieveTaskOutputs = 4028,
    InvalidTaskOutputSpecification = 4029,
    InvalidTaskParameterValueError = 4030,
    ItemSpecModifierCannotBeCustomMetadata = 4033,
    MissingRequiredAttribute = 4035,
    MissingTaskError = 4036,
    NodeMustBeLastUnderElement = 4038,
    NoRootProjectElement = 4039,
    NoTargetSpecified = 4040,
    ProjectMustBeInMSBuildXmlNamespace = 4041,
    QualifiedMetadataInTransformNotAllowed = 4043,
    RequiredPropertyNotSetError = 4044,
    SolutionParseErrorReadingProject = 4046,
    SolutionParseProjectDepNotFoundError = 4051,
    SolutionParseUpgradeNeeded = 4054,
    TargetDoesNotExist = 4057,
    TargetInputsSpecifiedWithoutOutputs = 4058,
    TaskDeclarationOrUsageError = 4060,
    TaskInstantiationFailureError = 4061,
    TaskLoadFailure = 4062,
    TaskParametersError = 4063,
    UnexpectedTaskAttribute = 4064,
    UnmarkedOutputTaskParameter = 4065,
    UnrecognizedAttribute = 4066,
    PropertyOutsidePropertyGroupInTarget = 4067,
    UnrecognizedChildElement = 4067,
    UnrecognizedElement = 4068,
    UnsupportedTaskParameterTypeError = 4069,
    UsingTaskAssemblySpecification = 4072,
    ProjectUpgradeNeeded = 4075,
    SolutionParseUnknownProjectType = 4078,
    DuplicateProjectExtensions = 4079,
    MultipleOtherwise = 4082,
    WhenNotAllowedAfterOtherwise = 4084,
    ChooseMustContainWhen = 4085,
    ComparisonOnNonNumericExpression = 4086,
    ConditionNotBoolean = 4087,
    IllFormedCondition = 4088,
    IncorrectNumberOfFunctionArguments = 4089,
    UnexpectedCharacterInCondition = 4090,
    UndefinedFunctionCall = 4091,
    UnexpectedTokenInCondition = 4092,
    SetAccessorNotAvailableOnTaskParameter = 4093,
    CannotPassMultipleItemsIntoScalarParameter = 4094,
    CannotReferenceItemMetadataWithoutItemName = 4095,
    ItemDoesNotContainValueForUnqualifiedMetadata = 4096,
    ItemListNotAllowedInThisConditional = 4099,
    ExpressionDoesNotEvaluateToBoolean = 4100,
    IllFormedQuotedStringInCondition = 4101,
    InvalidAttributeValueWithException = 4102,
    InvalidVerbosity = 4103,
    InvalidFileLoggerFile = 4104,
    IllFormedEqualsInCondition = 4105,
    IllFormedItemListCloseParenthesisInCondition = 4106,
    IllFormedItemListOpenParenthesisInCondition = 4107,
    IllFormedItemListQuoteInCondition = 4108,
    IllFormedPropertyCloseParenthesisInCondition = 4109,
    IllFormedPropertyOpenParenthesisInCondition = 4110,
    InvalidAttributeExclusive = 4111,
    SecurityProjectBuildDisabled = 4112,
    ConditionNotBooleanDetail = 4113,
    ChooseOverflow = 4114,
    CannotPassMultipleItemsIntoScalarFunction = 4115,
    TargetConditionHasInvalidMetadataReference = 4116,
    CannotModifyReservedItem = 4117,
    CannotModifyReservedItemMetadata = 4118,
    ItemReferencingSelfInTarget = 4120,
    SolutionProjectConfigurationMissing = 4121,
    SolutionScanProjectDependenciesFailed = 4122,
    SolutionParseInvalidProjectFileName = 4125,
    SolutionInvalidSolutionConfiguration = 4126,
    TaskInstantiationFailureErrorInvalidCast = 4127,
    ConditionMaybeEvaluatedIncorrectly = 4130,
    UnexpectedTaskOutputAttribute = 4131,
    DefaultToolsVersionNotFound = 4133,
    RegistryReadError = 4135,
    ConfigFileReadError = 4136,
    InvalidToolsetValueInConfigFileValue = 4137,
    NonStringDataInRegistry = 4138,
    MSBuildToolsPathIsNotSpecified = 4141,
    ConflictingValuesOfMSBuildToolsPath = 4142,
    InvalidRegistryPropertyExpression = 4143,
    MultipleDefinitionsForSameToolset = 4144,
    MultipleDefinitionsForSameProperty = 4145,
    ErrorEvaluatingToolsetPropertyExpression = 4146,
    InvalidPropertyNameInToolset = 4147,
    PropertyNameInRegistryHasZeroLength = 4148,
    SolutionToolsVersionDoesNotSupportProjectToolsVersion = 4149,
    MustCallInitializeBeforeApplyParameter = 4150,
    ErrorCreatingToolset = 4159,
    SolutionCircularDependencyError = 4160,
    ChildElementsBelowRemoveNotAllowed = 4162,
    ItemDefinitionGroupNotLegalInsideTarget = 4163,
    MetadataDefinitionCannotContainItemVectorExpression = 4164,
    ChildExitedPrematurely = 4166,
    InvalidChildElementDueToDuplication = 4173,
    CouldNotFindFactory = 4174,
    TaskFactoryLoadFailure = 4175,
    TaskFactoryInstantiationFailureErrorInvalidCast = 4176,
    InvalidProperty = 4177,
    TaskFactoryInstanceCreationError = 4179,
    LoggerInstantiationFailureErrorInvalidCast = 4180,
    TaskReturnedFalseButDidNotLogError = 4181,
    InvalidFunctionPropertyExpression = 4184,
    InvalidFunctionMethodUnavailable = 4185,
    InvalidFunctionStaticMethodSyntax = 4186,
    FailedToReceiveTaskThreadStatus = 4187,
    BuildAborted = 4188,
    UnrecognizedParentElement = 4189,
    BuiltInMetadataNotAllowedInThisConditional = 4190,
    CustomMetadataNotAllowedInThisConditional = 4191,
    ProjectUpgradeNeededToVcxProj = 4192,
    CouldNotFindMSBuildExe = 4193,
    OverrideTasksFileFailure = 4194,
    TasksPropertyBagError = 4195,
    OverrideTasksFileLoadFailureWarning = 4196,
    BuildAbortedWithMessage = 4197,
    InvalidItemFunctionExpression = 4198,
    InvalidItemFunctionSyntax = 4199,
    UnknownItemFunction = 4200,
    UnableToCancel = 4201,
    MainThreadInUse = 4202,
    AspNetCompiler_InvalidTargetFrameworkMonikerNotDotNET = 4203,
    AspNetCompiler_InvalidTargetFrameworkMonikerFromException = 4204,
    AspNetCompiler_20NotInstalled = 4205,
    InvalidHostObjectOnOutOfProcProject = 4206,
    InvalidAffinityForProjectWithHostObject = 4207,
    ProjectInstanceConflictsWithAffinity = 4209,
    SelfImport = 4210,
    UsedUninitializedProperty = 4211,
    InvalidFunctionTypeUnavailable = 4212,
    AffinityConflict = 4213,
    TaskExistsButHasMismatchedIdentityError = 4214,
    TaskLoadFailureInvalidTaskHostFactoryParameter = 4215,
    TaskHostAcquireFailed = 4216,
    TaskHostExitedPrematurely = 4217,
    CouldNotConnectToMSBuildExe = 4218,
    TaskFactoryWillIgnoreTaskFactoryParameters = 4219,
    UnableToCancelTask = 4220,
    TaskHostNodeFailedToLaunch = 4221,
    MSBuildToolsPathNotSupportedInSubToolsets = 4222,
    UnableToCreateNode = 4223,
    KeepAndRemoveMetadataMutuallyExclusive = 4224,
    MultipleDefinitionsForSameExtensionsPathOS = 4225,
    ImportedProjectFromExtensionsPathNotFound = 4226,
    ImportedProjectFromExtensionsPathNotFoundFromAppConfig = 4226,
    InvalidAttributeDueToDuplication = 4227,
    InvalidMetadataAsAttribute = 4228,
    FileToReloadFromDoesNotExist = 4229,
    InvalidSdkFormat = 4229,
    ValueNotSet = 4230,
    NoReloadOnUnsavedChanges = 4231,
    IncludeRemoveOrUpdate = 4232,
    InvalidBinaryLoggerParameters = 4234,
    UnsupportedLogFileFormat = 4235,
    CouldNotResolveSdk = 4236,
    CouldNotLoadSdkResolver = 4237,
    InvalidSdkElementName = 4238,
    ErrorWritingProfilerReport = 4239,
    ReferencingMultipleVersionsOfTheSameSdk = 4240,
    SdkResultVersionDifferentThanReference = 4241,
    SDKResolverCriticalFailure = 4242,
    CouldNotLoadSdkResolverAssembly = 4244,
    SdkResolverManifestInvalid = 4245,
    SdkResolverNoDllOrManifest = 4246,
    SdkResolverDllInManifestMissing = 4247,
    CannotExpandItemMetadata = 4248,
    AspNetCompiler_UnsupportedMSBuildVersion = 4249,
    ProjectGraphDoesNotSupportProjectReferenceWithToolset = 4250,
    CircularDependencyInProjectGraph = 4251,
    CacheMissesNotAllowedInIsolatedGraphBuilds = 4252,
    NullReferenceFromProjectInstanceFactory = 4253,
    UndeclaredMSBuildTasksNotAllowedInIsolatedGraphBuilds = 4254,
    InputCacheFilesDoNotExist = 4255,
    ErrorReadingCacheFile = 4256,
    EmptyOutputCacheFile = 4257,
    ErrorWritingCacheFile = 4258,
    IllFormedPropertySpaceInCondition = 4259,
    SkippedConstraintsOnRequest = 4260,
    StaticGraphAcceptsSingleSolutionEntryPoint = 4261,
    StaticGraphSolutionLoaderEncounteredSolutionWarningsAndErrors = 4262,
    StaticGraphDoesNotSupportSlnReferences = 4263,
    ProjectCacheInitializationFailed = 4266,
    ProjectCacheQueryFailed = 4267,
    ProjectCacheShutdownFailed = 4268,
    ProjectCacheHandleBuildResultFailed = 4269,
    NoProjectCachePluginFoundInAssembly = 4270,
    ChangeWave_InvalidFormat = 4271,
    ChangeWave_OutOfRotation = 4272,
    ProjectCacheException = 4273,
    ProxyRequestNotScheduledOnInprocNode = 4274,
    DuplicateOverrideUsingTaskElement = 4275,
    DefaultSDKResolverError = 4276,
    CannotCopyFromElementOfThatType = 4277,
    ImportedProjectFromVSDistribution = 4278,
    ErrorCopyingBinaryLog = 4279,
    DotnetHostPathIsDirectory = 4280,
    TaskInstantiationFailureNotSupported = 4802,
    SolutionParseDuplicateProject = 5004,
    SolutionParseInvalidProjectFileNameCharacters = 5005,
    SolutionParseInvalidProjectFileNameEmpty = 5006,
    SolutionParseInvalidProjectSolutionConfigurationEntry = 5007,
    SolutionParseInvalidSolutionConfigurationEntry = 5008,
    SolutionParseNestedProjectError = 5009,
    SolutionParseNestedProjectErrorWithNameAndGuid = 5009,
    SolutionParseNoHeaderError = 5010,
    SolutionParseProjectDepGuidError = 5011,
    SolutionParseProjectEofError = 5012,
    SolutionParseProjectError = 5013,
    SolutionParseVersionMismatchError = 5014,
    SolutionParseWebProjectPropertiesError = 5015,
    MalformedProjectFile = 5019,
    ProjectFileCouldNotBeLoaded = 5020,
    SolutionParseNestedProjectUndefinedError = 5023,
    SolutionFilterJsonParsingError = 5025,
    SolutionFilterMissingSolutionError = 5026,
    SolutionFilterFilterContainsProjectNotInSolution = 5028,

    /*
     * The command line message bucket is: MSB1001 - MSB1999
     *
     * Next error code should be MSB1072.
     *
     * Don't forget to update this comment after using the new code.
     */
    UnknownSwitchError = 1001,
    UnexpectedParametersError = 1002,
    MissingProjectError = 1003,
    MissingTargetError = 1004,
    MissingPropertyError = 1005,
    InvalidPropertyError = 1006,
    MissingLoggerError = 1007,
    DuplicateProjectSwitchError = 1008,
    ProjectNotFoundError = 1009,
    MissingGetPropertyError = 1010,
    AmbiguousProjectError = 1011,
    MissingResponseFileError = 1012,
    RepeatedResponseFileError = 1013,
    MissingGetItemError = 1014,
    UnsupportedOS = 1015,
    MissingVerbosityError = 1016,
    MissingGetTargetResultError = 1017,
    InvalidVerbosityError = 1018,
    InvalidLoggerError = 1019,
    XMake_LoggerNotFoundError = 1020,
    XMake_LoggerCreationError = 1021,
    ResponseFileNotFoundError = 1022,
    ReadResponseFileError = 1023,
    MultipleSchemasError = 1024,
    FatalError = 1025,
    SchemaNotFoundError = 1026,
    SchemaNotFoundErrorWithFile = 1026,
    CannotAutoDisableAutoResponseFile = 1027,
    LoggerFatalError = 1028,
    InvalidMaxCPUCountValue = 1030,
    MissingMaxCPUCountError = 1031,
    InvalidMaxCPUCountValueOutsideRange = 1032,
    InvalidNodeNumberValue = 1033,
    InvalidNodeNumberValueIsNegative = 1034,
    MissingIgnoreProjectExtensionsError = 1035,
    InvalidExtensionToIgnore = 1036,
    MissingConsoleLoggerParameterError = 1037,
    MissingFileLoggerParameterError = 1038,
    MissingToolsVersionError = 1039,
    InvalidToolsVersionError = 1040,
    MissingNodeReuseParameterError = 1041,
    InvalidNodeReuseTrueValue = 1042,
    InvalidNodeReuseValue = 1042,
    InvalidPreprocessPath = 1047,
    DebuggingSolutionFiles = 1048,
    ParameterRequiredError = 1049,
    AmbiguousProjectDirectoryError = 1050,
    MissingWarnAsMessageParameterError = 1051,
    InvalidRestoreValue = 1052,
    InvalidProfilerValue = 1053,
    InvalidInteractiveValue = 1055,
    InvalidIsolateProjectsValue = 1056,
    InvalidGraphBuildValue = 1057,
    DuplicateOutputResultsCache = 1058,
    TargetsCouldNotBePrinted = 1059,
    EnvironmentVariableAsSwitch = 1060,
    MissingWarnNotAsErrorParameterError = 1060,
    InvalidDetailedSummaryValue = 1061,
    NotWarnAsErrorWithoutWarnAsError = 1062,
    InvalidReportFileAccessesValue = 1063,
    SolutionBuildInvalidForCommandLineEvaluation = 1063,
    InvalidLowPriorityValue = 1064,
    InvalidTerminalLoggerValue = 1065,
    MissingTerminalLoggerParameterError = 1066,
    MissingFeatureAvailabilityError = 1067,
    MissingGetResultFileError = 1068,
    LoggingArgsEnvVarUnsupportedArgument = 1070,
    InvalidNoLogoValue = 1071,
    LoggingArgsEnvVarError = 1071,
    XMake_ProjectUpgradeNeededToVcxProj = 4192,
    InvalidLogFileFormat = 4233,
    BuildEngineCallbacksInTaskHostUnsupported = 5022,

    /*
     * The tasks message bucket is: MSB3001 - MSB3999
     *
     * See the comments above each task's messages for individual task message buckets.
     *
     * If you need a new bucket, please update the master bucket list below:
     *     MSB3001 - MSB3010   Task: AssignCulture
     *     MSB3011 - MSB3020   Task: AL
     *     MSB3021 - MSB3030   Task: Copy
     *     MSB3031 - MSB3040   Task: CreateItem
     *     MSB3041 - MSB3050   Task: CreateManifestResourceName
     *     MSB3051 - MSB3060   Task: Csc
     *     MSB3061 - MSB3070   Task: Delete
     *     MSB3071 - MSB3080   Task: Exec
     *     MSB3081 - MSB3109   Task: General                 // MSB3109 not used but already shipped, do not reuse
     *     MSB3110 - MSB3130   Task: GenerateManifest overflow
     *     MSB3131 - MSB3140   Task: GetRedistListPaths      // DEAD DO NOT REUSE BLOCK
     *     MSB3141 - MSB3170   Task: GenerateBootstrapper    // MSB3167 not used but already shipped, do not reuse
     *     MSB3171 - MSB3190   Task: GenerateManifest
     *     MSB3191 - MSB3200   Task: MakeDir
     *     MSB3201 - MSB3210   Task: MSBuild
     *     MSB3211 - MSB3230   Task: RegisterAssembly
     *     MSB3231 - MSB3240   Task: RemoveDir
     *     MSB3241 - MSB3280   Task: ResolveAssemblyReference
     *     MSB3281 - MSB3320   Task: ResolveComReference
     *     MSB3321 - MSB3330   Task: ResolveKeySource
     *     MSB3331 - MSB3340   Task: ResolveManifestFiles
     *     MSB3341 - MSB3350   Task: ResolveNativeReference
     *     MSB3351 - MSB3360   Task: StrongNameUtils
     *     MSB3361 - MSB3370   Task: ToolTask
     *     MSB3371 - MSB3390   Task: Touch
     *     MSB3391 - MSB3400   Task: UnregisterAssembly
     *     MSB3401 - MSB3410   Task: Vbc
     *     MSB3411 - MSB3420   Task: VCBuild                     // DEAD DO NOT REUSE BLOCK
     *     MSB3421 - MSB3440   Task: ResolveVCProjectOutput      // DEAD DO NOT REUSE BLOCK
     *     MSB3441 - MSB3450   Task: GetAssemblyIdentity
     *     MSB3451 - MSB3460   Task: ResGen
     *     MSB3461 - MSB3470   Task: AspNetCompiler
     *     MSB3471 - MSB3480   Task: SGen
     *     MSB3481 - MSB3490   Task: SignFile    // MSB3485 MSB3486 not used but already shipped, do not reuse
     *     MSB3491 - MSB3500   Task: WriteLinesToFile
     *     MSB3501 - MSB3510   Task: ReadLinesFromFile
     *     MSB3511 - MSB3520   Task: Message
     *     MSB3521 - MSB3530   Task: Warning
     *     MSB3531 - MSB3540   Task: Error    // MSB3539, MSB3540 is used in Microsoft.Common.CurrentVersion.targets, do not reuse
     *     MSB3541 - MSB3550   Task: FindUnderPath
     *     MSB3551 - MSB3580   Task: GenerateResource     // MSB3561, MSB3571 not used but already shipped, do not reuse
     *     MSB3581 - MSB3600   Task: ResolveNonMSBuildProjectOutput
     *     MSB3601 - MSB3610   Task: ResolveProjectConfiguration
     *     MSB3611 - MSB3620   Task: CreateTemporaryVCProject    // DEAD DO NOT REUSE BLOCK
     *     MSB3621 - MSB3641   Task: General overflow
     *     MSB3642 - MSB3646   Task: GetReferenceAssemblyPaths
     *     MSB3646 - MSB3655   Task: AxTlbBaseTask
     *     MSB3656 - MSB3660   Task: AxImp
     *     MSB3661 - MSB3665   Task: TlbImp
     *     MSB3666 - MSB3675   Task: General
     *     MSB3676 - MSB3685   Task: Move
     *     MSB3686 - MSB3695   Task: XamlTaskFactory
     *     MSB3696 - MSB3700   Task: GenerateBootstrapper overflow
     *     MSB3701 - MSB3710   Task: XslTransformation
     *     MSB3711 - MSB3720   Task: WriteCodeFragment
     *     MSB3721 - MSB3730   Task: XamlTaskFactory overflow
     *     MSB3731 - MSB3740   Task: XmlPoke
     *     MSB3741 - MSB3750   Task: XmlPeek
     *     MSB3751 - MSB3761   Task: CodeTaskFactory
     *     MSB3762 - MSB3772   Task: WinMDExp
     *     MSB3773 - MSB3783   Task: ResolveSDKReference
     *     MSB3784 - MSB3794   Task: GetInstalledSDKs
     *     MSB3795 - MSB3810   Task: GetSDKReferenceFiles
     *     MSB3811 - MSB3830   Task: GenerateResource
     *     MSB3831 - MSB3840   Task: GenerateBindingRedirects
     *     MSB3841 - MSB3850   Task: ResolveSDKReference (additional error messages)
     *     MSB3851 - MSB3860   Task: FindInvalidProjectReferences
     *     MSB3861 - MSB3870   Task: ErrorFromResources
     *     MSB3871 - MSB3880   Targets: Code sharing
     *     MSB3881 - MSB3890   Task: Compiler
     *     MSB3891 - MSB3900   Overflow: Copy
     *     MSB3901 - MSB3910   Task: Telemetry
     *     MSB3911 - MSB3920   Task: CodeTaskFactory
     *     MSB3921 - MSB3930   Task: DownloadFile
     *     MSB3931 - MSB3940   Task: Unzip
     *     MSB3941 - MSB3950   Task: ZipDirectory
     *     MSB3951 - MSB3960   Task: VerifyFileHash
     *     MSB3961 - MSB3970   Task: GenerateLauncher
     *     MSB3971 - MSB3980   Task: GetReferenceAssemblyPaths overflow
     *     MSB3981 - MSB3990   Task: GetCompatiblePlatform
     *     MSB3991 - MSB3999   Task: CombineTargetFrameworkInfoProperties
     *     MSB4300 - MSB4310   Task: AddToWin32Manifest
     *
     *     MSB4000 - MSB4200   Portable targets & tasks (vsproject\flavors\portable\msbuild)
     *     MSB9000 - MSB9900   MSBuild targets files (C++)
     *
     *     MSB9901 - MSB9990   MSBuild common targets messages
     *
     * The following codes are not longer used but have shipped so should not be reused:
     *     MSB3109
     *     MSB3493
     *
     *
     * The message spec is here:
     *    http://msbuild/wiki/default.aspx/MSBuild.GenerateResourceTaskMessages
     *
     * Codes only need to be applied to messages that are logged as errors/warnings. Messages thrown with exceptions do NOT need
     * error codes, because those exceptions should ideally be caught at a higher scope and logged with a wrapper message that
     * DOES have an error code.
     */
    AssignCulture_CannotExtractCulture = 3001,
    AssignCulture_CultureOverwritten = 3002,
    Copy_Error = 3021,
    Copy_ExactlyOneTypeOfDestination = 3022,
    Copy_NeedsDestination = 3023,
    Copy_DestinationIsDirectory = 3024,
    Copy_SourceIsDirectory = 3025,
    Copy_Retrying = 3026,
    Copy_ExceededRetries = 3027,
    Copy_InvalidRetryCount = 3028,
    Delete_InvalidRetryCount = 3028,
    Copy_InvalidRetryDelay = 3029,
    Delete_InvalidRetryDelay = 3029,
    Copy_SourceFileNotFound = 3030,
    CreateItem_AdditionalMetadataError = 3031,
    CreateManifestResourceName_Error = 3041,
    CreateManifestResourceName_DefinitionFoundWithinConditionalDirective = 3042,
    Csc_InvalidParameter = 3051,
    Csc_InvalidParameterWarning = 3052,
    Csc_AssemblyAliasContainsIllegalCharacters = 3053,
    Delete_Error = 3061,
    Delete_Retrying = 3062,
    Exec_AllDriveLettersMappedError = 3071,
    Exec_MissingCommandError = 3072,
    Exec_CommandFailed = 3073,
    Exec_CommandFailedAccessDenied = 3075,
    Exec_InvalidRegex = 3076,
    Exec_CommandExitedZeroWithErrors = 3077,
    General_CouldNotSetHostObjectParameter = 3081,
    General_FrameworksFileNotFound = 3082,
    General_DuplicateItemsNotSupportedWithMetadata = 3083,
    General_PlatformSDKFileNotFoundSdkToolsPath = 3084,
    General_SdkToolsPathToolDoesNotExist = 3086,
    General_IncorrectHostObject = 3087,
    General_CouldNotReadStateFile = 3088,
    General_PlatformSDKFileNotFound = 3091,
    General_ToolCommandFailed = 3093,
    General_InvalidArgument = 3095,
    General_TaskRequiresWindows = 3096,
    General_InvalidAssembly = 3097,
    General_InvalidValue = 3098,
    General_InvalidAssemblyName = 3099,
    General_CouldNotWriteStateFile = 3101,
    General_CouldNotDeleteStateFile = 3102,
    General_InvalidResxFile = 3103,
    General_ReferenceDoesNotExist = 3104,
    General_DuplicateItemsNotSupported = 3105,
    General_MalformedAssemblyName = 3106,
    General_MissingOrUnknownProjectReferenceAttribute = 3107,
    General_ErrorExecutingTask = 3108,
    GenerateManifest_IdentityFileNameMismatch = 3110,
    GenerateManifest_ConfigBindingRedirectsWithPartialTrust = 3111,
    GenerateManifest_DuplicateAssemblyIdentity = 3112,
    GenerateManifest_ResolveFailedInReadWriteMode = 3113,
    GenerateManifest_ResolveFailedInReadOnlyMode = 3114,
    GenerateManifest_InvalidEntryPoint = 3115,
    GenerateManifest_HostInBrowserNotOnlineOnly = 3116,
    GenerateManifest_HostInBrowserInvalidFrameworkVersion = 3117,
    GenerateManifest_FileAssociationExtensionMissingLeadDot = 3119,
    GenerateManifest_FileAssociationExtensionTooLong = 3120,
    GenerateManifest_FileAssociationMissingAttribute = 3121,
    GenerateManifest_FileAssociationsApplicationNotFullTrust = 3122,
    GenerateManifest_FileAssociationsCountExceedsMaximum = 3123,
    GenerateManifest_FileAssociationsDuplicateExtensions = 3124,
    GenerateManifest_FileAssociationsNoEntryPoint = 3125,
    GenerateManifest_FileAssociationsNotInstalled = 3126,
    GenerateManifest_FileAssociationDefaultIconNotInstalled = 3127,
    GenerateManifest_ManifestsSignedHashExcluded = 3128,
    GenerateManifest_ExcludedPermissionsNotSupported = 3133,
    GenerateManifest_KnownTargetZoneCannotHaveAdditionalPermissionType = 3134,
    GenerateManifest_NoPermissionSetForTargetZone = 3135,
    GenerateBootstrapper_MissingVerificationInformation = 3141,
    GenerateBootstrapper_CopyError = 3142,
    GenerateBootstrapper_CopyPackageError = 3143,
    GenerateBootstrapper_InvalidInput = 3144,
    GenerateBootstrapper_InvalidUrl = 3145,
    GenerateBootstrapper_MissingDependency = 3146,
    GenerateBootstrapper_MissingSetupBin = 3147,
    GenerateBootstrapper_NoOutputPath = 3148,
    GenerateBootstrapper_NoResources = 3149,
    GenerateBootstrapper_NoStringsForCulture = 3150,
    GenerateBootstrapper_IncludedProductIncluded = 3151,
    GenerateBootstrapper_PackageFileNotFound = 3152,
    GenerateBootstrapper_PackageValidation = 3153,
    GenerateBootstrapper_ProductCultureNotFound = 3154,
    GenerateBootstrapper_ProductNotFound = 3155,
    GenerateBootstrapper_ProductValidation = 3156,
    GenerateBootstrapper_UsingProductCulture = 3157,
    GenerateBootstrapper_UsingResourcesCulture = 3158,
    GenerateBootstrapper_ValidationError = 3159,
    GenerateBootstrapper_ValidationWarning = 3160,
    GenerateBootstrapper_CircularDependency = 3161,
    GenerateBootstrapper_DependencyNotFound = 3162,
    GenerateBootstrapper_InvalidComponentsLocation = 3163,
    GenerateBootstrapper_PackageHomeSiteMissing = 3164,
    GenerateBootstrapper_DifferingPublicKeys = 3165,
    GenerateBootstrapper_PackageResourceFileNotFound = 3166,
    GenerateBootstrapper_DuplicateItems = 3168,
    GenerateBootstrapper_General = 3169,
    GenerateBootstrapper_MultipleDependeciesNotFound = 3170,
    GenerateManifest_General = 3171,
    GenerateManifest_ReadInputManifestFailed = 3172,
    GenerateManifest_WriteOutputManifestFailed = 3173,
    GenerateManifest_InvalidValue = 3174,
    GenerateManifest_InvalidItemValue = 3175,
    GenerateManifest_GreaterMinimumRequiredVersion = 3176,
    GenerateManifest_AllowPartiallyTrustedCallers = 3177,
    GenerateManifest_AssemblyAsFile = 3178,
    GenerateManifest_ComImport = 3179,
    GenerateManifest_DuplicateComDefinition = 3180,
    GenerateManifest_DuplicateTargetPath = 3181,
    GenerateManifest_TargetPathTooLong = 3182,
    GenerateManifest_UnmanagedCodePermission = 3183,
    GenerateManifest_InvalidInputManifest = 3184,
    GenerateManifest_NoEntryPoint = 3185,
    GenerateManifest_NoIdentity = 3186,
    GenerateManifest_PlatformMismatch = 3187,
    GenerateManifest_PrerequisiteNotSigned = 3188,
    GenerateManifest_InvalidDeploymentProvider = 3189,
    GenerateManifest_InvalidRequestedExecutionLevel = 3190,
    MakeDir_Error = 3191,
    RegisterAssembly_AssemblyNotRegisteredForComInterop = 3211,
    RegisterAssembly_CantExportTypeLib = 3212,
    RegisterAssembly_CantRegisterTypeLib = 3213,
    RegisterAssembly_NoValidTypes = 3214,
    RegisterAssembly_RegisterAsmFileDoesNotExist = 3215,
    RegisterAssembly_UnauthorizedAccess = 3216,
    RegisterAssembly_CantRegisterAssembly = 3217,
    RemoveDir_Error = 3231,
    RemoveDir_EmptyPath = 3232,
    ResolveAssemblyReference_ConflictBetweenAppConfigAndAutoUnify = 3242,
    ResolveAssemblyReference_ConflictUnsolvable = 3243,
    ResolveAssemblyReference_FailedToFindDependentFiles = 3244,
    ResolveAssemblyReference_FailedToResolveReference = 3245,
    ResolveAssemblyReference_FailedWithException = 3246,
    ResolveAssemblyReference_SuggestedRedirects = 3247,
    ResolveAssemblyReference_InvalidParameter = 3248,
    ResolveAssemblyReference_InvalidAppConfig = 3249,
    ResolveAssemblyReference_InvalidInstalledAssemblyTablesFile = 3250,
    ResolveAssemblyReference_FailedToResolveReferenceBecauseHigherTargetFramework = 3251,
    ResolveAssemblyReference_FailedToResolveReferenceBecausePrimaryAssemblyInExclusionList = 3252,
    ResolveAssemblyReference_FailBecauseDependentAssemblyInExclusionList = 3253,
    ResolveAssemblyReference_InvalidInstalledAssemblySubsetTablesFile = 3254,
    ResolveAssemblyReference_NoSubsetsFound = 3255,
    ResolveAssemblyReference_NoRedistAssembliesToGenerateExclusionList = 3256,
    ResolveAssemblyReference_PrimaryReferenceOutsideOfFramework = 3257,
    ResolveAssemblyReference_DependencyReferenceOutsideOfFramework = 3258,
    ResolveAssemblyReference_CannotSetProfileAndSubSet = 3259,
    ResolveAssemblyReference_NoProfilesFound = 3260,
    ResolveAssemblyReference_FrameworkDirectoryOnProfiles = 3261,
    ResolveAssemblyReference_MustSetProfileNameAndFolderLocations = 3262,
    ResolveAssemblyReference_InvalidProfileRedistLocation = 3263,
    ResolveAssemblyReference_PrimaryReferenceInAnotherFramework = 3267,
    ResolveAssemblyReference_DependencyReferenceInAnotherFramework = 3268,
    ResolveAssemblyReference_ProblemDeterminingFrameworkMembership = 3269,
    ResolveAssemblyReference_MismatchBetweenTargetedAndReferencedArch = 3270,
    ResolveAssemblyReference_MismatchBetweenTargetedAndReferencedArchOfImplementation = 3271,
    ResolveAssemblyReference_ProblemReadingImplementationDll = 3272,
    ResolveAssemblyReference_UnknownProcessorArchitecture = 3273,
    ResolveAssemblyReference_PrimaryReferenceOutsideOfFrameworkUsingAttribute = 3274,
    ResolveAssemblyReference_DependencyReferenceOutsideOfFrameworkUsingAttribute = 3275,
    ResolveAssemblyReference_TurnOnAutoGenerateBindingRedirects = 3276,
    ResolveAssemblyReference_FoundConflicts = 3277,
    ResolveComReference_BadAssemblyImage = 3281,
    ResolveComReference_CannotAccessTypeLibName = 3282,
    ResolveComReference_CannotFindWrapperForTypeLib = 3283,
    ResolveComReference_CannotGetPathForTypeLib = 3284,
    ResolveComReference_CannotGetTypeLibAttrForTypeLib = 3285,
    ResolveComReference_CannotLoadTypeLib = 3286,
    ResolveComReference_CannotLoadTypeLibItemSpec = 3287,
    ResolveComReference_ConflictingReferences = 3288,
    ResolveComReference_ErrorCreatingWrapperAssembly = 3290,
    ResolveComReference_FailedToFindDependentNetAssembly = 3291,
    ResolveComReference_FailedToRemapAdoTypeLib = 3292,
    ResolveComReference_FailedToResolveDependentComReference = 3293,
    ResolveComReference_FailedToResolveDependentComReferenceByAssemblyName = 3294,
    ResolveComReference_LoadingDelaySignedAssemblyWithStrongNameVerificationEnabled = 3295,
    ResolveComReference_MissingOrUnknownComReferenceAttribute = 3296,
    ResolveComReference_NoComReferencesSpecified = 3297,
    ResolveComReference_StrongNameUtils_NoKeyPairInContainer = 3298,
    ResolveComReference_StrongNameUtils_NoKeyPairInFile = 3299,
    ResolveComReference_CannotSpecifyBothKeyFileAndKeyContainer = 3300,
    ResolveComReference_CannotSpecifyDelaySignWithoutEitherKeyFileOrKeyContainer = 3301,
    ResolveComReference_CannotRetrieveTypeInformation = 3302,
    ResolveComReference_FailedToResolveComReference = 3303,
    ResolveComReference_FailedToScanDependencies = 3304,
    ResolveComReference_ResolutionWarning = 3305,
    ResolveKeySource_KeyImportError = 3321,
    ResolveKeySource_KeyMD5SumError = 3322,
    ResolveKeySource_CertificateNotInStore = 3323,
    ResolveKeySource_InvalidKeyName = 3324,
    ResolveKeySource_KeyFileForSignAssemblyNotImported = 3325,
    ResolveKeySource_KeyFileForManifestNotImported = 3326,
    ResolveKeySource_ResolvedThumbprintEmpty = 3327,
    ResolveManifestFiles_PublishFileNotFound = 3331,
    ResolveNativeReference_FailedToResolveReference = 3341,
    StrongNameUtils_BadKeyContainer = 3351,
    StrongNameUtils_KeyFileReadFailure = 3352,
    StrongNameUtils_NoPublicKeySpecified = 3353,
    Touch_CannotCreateFile = 3371,
    Touch_CannotMakeFileWritable = 3372,
    Touch_CannotRestoreAttributes = 3373,
    Touch_CannotTouch = 3374,
    Touch_FileDoesNotExist = 3375,
    Touch_TimeSyntaxIncorrect = 3376,
    UnregisterAssembly_NoValidTypes = 3391,
    UnregisterAssembly_UnauthorizedAccess = 3392,
    UnregisterAssembly_UnregisterAsmFileDoesNotExist = 3393,
    UnregisterAssembly_UnregisterTlbFileNotRegistered = 3394,
    UnregisterAssembly_CantUnregisterAssembly = 3395,
    UnregisterAssembly_AssemblyPathOrStateFileIsRequired = 3396,
    UnregisterAssembly_UnregisterTlbCantLoadFile = 3397,
    Vbc_EnumParameterHasInvalidValue = 3401,
    VBC_RenamePDB = 3402,
    GetAssemblyIdentity_CouldNotGetAssemblyName = 3441,
    ResGen_SdkOrToolPathNotSpecifiedOrInvalid = 3451,
    ResGen_STRClassNamespaceOrFilenameWithoutLanguage = 3452,
    ResGen_STRLanguageButNotExactlyOneSourceFile = 3453,
    ResGen_TrackerNotFound = 3454,
    ResGen_CommandTooLong = 3455,
    AspNetCompiler_CannotCombineMetabaseAndVirtualPathOrPhysicalPath = 3461,
    AspNetCompiler_MissingMetabasePathAndVirtualPath = 3462,
    AspNetCompiler_MissingTargetPathForUpdatableApplication = 3463,
    AspNetCompiler_MissingTargetPathForOverwrittenApplication = 3464,
    SGen_ResourceNotFound = 3471,
    SGen_CouldNotDeleteSerializer = 3472,
    SGen_InvalidPath = 3473,
    SGen_TaskNotSupported = 3474,
    SignFile_CertNotInStore = 3481,
    SignFile_SignToolError = 3482,
    SignFile_SignToolWarning = 3483,
    SignFile_TargetFileNotFound = 3484,
    SignFile_CertMissingPrivateKey = 3487,
    WriteLinesToFile_ErrorOrWarning = 3491,
    WriteLinesToFile_ErrorReadingFile = 3492,
    WriteLinesToFile_ErrorReadingFileTransactional = 3494,
    ReadLinesFromFile_ErrorOrWarning = 3501,
    CommonSdk_BaseIntermediateOutputPathMismatchWarning = 3539,
    CommonSdk_MSBuildProjectExtensionsPathModifiedAfterUse = 3540,
    FindUnderPath_InvalidParameter = 3541,
    GenerateResource_ResourceNotFound = 3552,
    GenerateResource_InvalidFilename = 3553,
    GenerateResource_CannotWriteOutput = 3554,
    GenerateResource_OnlyStringsSupported = 3556,
    GenerateResource_ErrorFromCodeDom = 3557,
    GenerateResource_UnknownFileExtension = 3558,
    GenerateResource_STRCodeDomProviderFailed = 3559,
    GenerateResource_DeleteCorruptOutputFailed = 3560,
    GenerateResource_ObsoleteStringsTag = 3562,
    GenerateResource_UnexpectedInfBracket = 3563,
    GenerateResource_NoEqualsInLine = 3564,
    GenerateResource_NoNameInLine = 3565,
    GenerateResource_InvalidEscape = 3566,
    GenerateResource_CodeDomError = 3567,
    GenerateResource_DuplicateResourceName = 3568,
    GenerateResource_InvalidHexEscapeValue = 3569,
    GenerateResource_CannotWriteSTRFile = 3570,
    GenerateResource_STRClassNamespaceOrFilenameWithoutLanguage = 3572,
    GenerateResource_STRLanguageButNotExactlyOneSourceFile = 3573,
    GenerateResource_BadImageFormat = 3574,
    GenerateResource_CannotWriteAssembly = 3575,
    GenerateResource_CreatingCultureInfoFailed = 3576,
    GenerateResource_DuplicateOutputFilenames = 3577,
    GenerateResource_NeutralityOfCultureNotPreserved = 3578,
    GenerateResource_NoResourcesFileInAssembly = 3579,
    GenerateResource_SatelliteOrMalformedAssembly = 3580,
    ResolveNonMSBuildProjectOutput_ProjectReferenceResolutionFailure = 3582,
    GetReferenceAssemblyPaths_InvalidTargetFrameworkMoniker = 3642,
    GetReferenceAssemblyPaths_ProblemGeneratingReferencePaths = 3643,
    GetReferenceAssemblyPaths_NoReferenceAssemblyDirectoryFound = 3644,
    GetReferenceAssemblyPaths_NETFX35SP1NotIntstalled = 3645,
    AxTlbBaseTask_CannotSpecifyBothKeyFileAndKeyContainer = 3646,
    AxTlbBaseTask_CannotSpecifyDelaySignWithoutEitherKeyFileOrKeyContainer = 3647,
    AxTlbBaseTask_InvalidKeyFileSpecified = 3649,
    AxTlbBaseTask_SdkOrToolPathNotSpecifiedOrInvalid = 3650,
    AxTlbBaseTask_StrongNameUtils_NoKeyPairInContainer = 3651,
    AxTlbBaseTask_StrongNameUtils_NoKeyPairInFile = 3652,
    AxTlbBaseTask_ToolNameMustBeSet = 3653,
    AxTlbBaseTask_StrongNameUtils_NoPublicKeySpecified = 3654,
    AxImp_NoInputFileSpecified = 3656,
    TlbImp_InvalidTransformParameter = 3661,
    TlbImp_NoInputFileSpecified = 3662,
    General_SdkToolsPathError = 3666,
    General_StateFileAlreadyPresent = 3667,
    Move_DestinationIsDirectory = 3676,
    Move_Error = 3677,
    Move_ExactlyOneTypeOfDestination = 3678,
    Move_NeedsDestination = 3679,
    Move_SourceDoesNotExist = 3680,
    Move_SourceIsDirectory = 3681,
    Xaml_TaskCreationFailed = 3686,
    Xaml_RuleParseFailed = 3687,
    Xaml_RuleFileNotFound = 3688,
    Xaml_RuleMissingToolName = 3689,
    Xaml_RuleNotFound = 3690,
    Xaml_InvalidRootObject = 3691,
    Xaml_MissingTaskBody = 3692,
    Xaml_ArgumentOutOfRange = 3693,
    Xaml_MissingSwitchValue = 3694,
    GenerateBootstrapper_MissingDependencyMultiple = 3696,
    XslTransform_ArgumentError = 3701,
    XslTransform_XsltArgumentsError = 3702,
    XslTransform_TransformError = 3703,
    XslTransform_XsltLoadError = 3704,
    XslTransform_PrecompiledXsltError = 3705,
    WriteCodeFragment_MustSpecifyLocation = 3711,
    WriteCodeFragment_CouldNotCreateProvider = 3712,
    WriteCodeFragment_CouldNotWriteOutput = 3713,
    WriteCodeFragment_SkippedNumberedParameter = 3714,
    WriteCodeFragment_ParameterTypeNotFound = 3715,
    WriteCodeFragment_CouldNotConvertValue = 3716,
    Xaml_CommandFailed = 3721,
    Xaml_CommandFailedAccessDenied = 3722,
    Xaml_MissingRequiredArgument = 3723,
    Xaml_DuplicatePropertyName = 3724,
    Xaml_CommandExitedZeroWithErrors = 3725,
    XmlPoke_NamespacesError = 3731,
    XmlPoke_XPathContextError = 3732,
    XmlPeekPoke_InputFileError = 3733,
    XmlPeekPoke_XPathError = 3734,
    XmlPoke_PokeError = 3735,
    XmlPeek_ArgumentError = 3741,
    XmlPeek_NamespacesError = 3742,
    XmlPeek_XPathContextError = 3743,
    CodeTaskFactory_CodeElementIsMissing = 3751,
    CodeTaskFactory_AttributeEmpty = 3752,
    CodeTaskFactory_AttributeEmptyWithElement = 3752,
    CodeTaskFactory_AttributeEmptyWithTaskElement = 3752,
    CodeTaskFactory_NeedsITaskInterface = 3753,
    CodeTaskFactory_ReferenceAssemblyIsInvalid = 3754,
    CodeTaskFactory_CouldNotFindReferenceAssembly = 3755,
    CodeTaskFactory_InvalidCodeElementAttribute = 3756,
    CodeTaskFactory_InvalidElementLocation = 3756,
    CodeTaskFactory_MultipleCodeNodes = 3757,
    CodeTaskFactory_CompilerError = 3758,
    CodeTaskFactory_InvalidCodeLanguage = 3759,
    CodeTaskFactory_InvalidCodeType = 3759,
    CodeTaskFactory_NoSourceCode = 3760,
    CodeTaskFactory_InvalidTaskXml = 3761,
    WinMDExp_MustPassReferences = 3762,
    ResolveSDKReference_CannotReferenceTwoSDKsSameFamily = 3773,
    ResolveSDKReference_CouldNotResolveSDK = 3774,
    ResolveSDKReference_ErrorResolvingSDK = 3775,
    ResolveSDKReference_SDKReferenceIncorrectFormat = 3776,
    ResolveSDKReference_NoMatchingFrameworkIdentity = 3777,
    ResolveSDKReference_NoMatchingAppxLocation = 3778,
    ResolveSDKReference_TargetArchitectureNotSupported = 3779,
    ResolveSDKReference_CannotReferenceTwoSDKsSameName = 3780,
    ResolveSDKReference_SDKMissingDependency = 3781,
    ResolveSDKReference_Prefer32BitNotSupportedWithNeutralProject = 3782,
    ResolveSDKReference_MaxPlatformVersionLessThanTargetPlatformVersion = 3783,
    GetInstalledSDKs_TargetPlatformInformationMissing = 3784,
    GetInstalledSDKs_NoSDksFound = 3785,
    GetInstalledSDKs_CouldNotGetSDKList = 3786,
    GetSDKReferenceFiles_CouldNotGetSDKReferenceFiles = 3795,
    GetSDKReferenceFiles_ConflictBetweenFiles = 3796,
    GetSDKReferenceFiles_CannotHaveEmptyTargetConfiguration = 3797,
    GetSDKReferenceFiles_CannotHaveEmptyTargetArchitecture = 3798,
    GenerateResource_SatelliteAssemblyContainsCode = 3811,
    GenerateResource_SatelliteAssemblyContainsNoResourcesFile = 3812,
    GenerateResource_UnrecognizedUltimateResourceFallbackLocation = 3813,
    GenerateResource_ImproperlyBuiltMainAssembly = 3814,
    GenerateResource_ImproperlyBuiltSatelliteAssembly = 3815,
    GenerateResource_CannotLoadAssemblyLoadFromFailed = 3816,
    GenerateResource_MainAssemblyMissingNeutralResourcesLanguage = 3817,
    GenerateResource_ExecuteAsToolAndExtractResWNotSupported = 3818,
    GenerateResource_MissingFile = 3819,
    GenerateResource_PathTooLong = 3820,
    GenerateResource_MOTW = 3821,
    GenerateResource_PreserializedResourcesRequiresExtensions = 3822,
    GenerateResource_PreserializedResourcesRequiresProperty = 3823,
    GenerateResource_CoreSupportsLimitedScenarios = 3824,
    GenerateResource_BinaryFormatterUse = 3825,
    GenerateResource_MimeTypeNotSupportedOnCore = 3826,
    GenerateResource_STRPropertySkippedReservedName = 3827,
    GenerateResource_STRPropertySkippedInvalidIdentifier = 3828,
    GenerateResource_STRPropertySkippedNameCollision = 3829,
    GenerateResource_STRPropertySkippedVoidType = 3830,
    GenerateBindingRedirects_MissingConfigurationNode = 3831,
    GenerateBindingRedirects_MalformedVersionNumber = 3832,
    GenerateBindingRedirects_MalformedAssemblyName = 3833,
    GenerateBindingRedirects_MissingNode = 3835,
    GenerateBindingRedirects_OverlappingBindingRedirect = 3836,
    ResolveSDKReference_InvalidDependencyInPlatform = 3841,
    ResolveSDKReference_MaxPlatformVersionNotSpecified = 3842,
    ResolveSDKReference_TargetPlatformIdentifierDoesNotMatch = 3843,
    ResolveSDKReference_PlatformVersionIsLessThanMinVersion = 3844,
    FindInvalidProjectReferences_WarnWhenVersionIsIncompatible = 3851,
    ErrorFromResources_LogErrorFailure = 3861,
    CodeSharing_CannotBuildSharedProject = 3871,
    Compiler_FatalArguments = 3881,
    Compiler_FatalNoResponse = 3882,
    Compiler_UnexpectedException = 3883,
    Compiler_UnableToFindRuleSet = 3884,
    Copy_ErrorIfLinkFailsSetWithoutLinkOption = 3892,
    Copy_LinkFailed = 3893,
    Copy_IOException = 3894,
    Copy_RetryingOnAccessDenied = 3895,
    Copy_IncompatibleParameters = 3896,
    DownloadFile_ErrorInvalidUrl = 3921,
    DownloadFile_ErrorUnknownFileName = 3922,
    DownloadFile_ErrorDownloading = 3923,
    DownloadFile_Retrying = 3924,
    Unzip_ErrorCouldNotCreateDestinationDirectory = 3931,
    Unzip_ErrorFileDoesNotExist = 3932,
    Unzip_ErrorCouldNotOpenFile = 3933,
    Unzip_ErrorExtractingResultsInFilesOutsideDestination = 3934,
    Unzip_ErrorCouldNotMakeFileWriteable = 3935,
    Unzip_ErrorCouldNotExtractFile = 3936,
    Unzip_ErrorParsingPatternInvalidPath = 3937,
    Unzip_ErrorParsingPatternPropertyReferences = 3938,
    ZipDirectory_ErrorDirectoryDoesNotExist = 3941,
    ZipDirectory_ErrorFileExists = 3942,
    ZipDirectory_ErrorFailed = 3943,
    ZipDirectory_ErrorInvalidCompressionLevel = 3944,
    ZipDirectory_WarningCompressionLevelUnsupportedOnFramework = 3945,
    FileHash_UnrecognizedHashEncoding = 3951,
    VerifyFileHash_HashMismatch = 3952,
    FileHash_UnrecognizedHashAlgorithm = 3953,
    FileHash_FileNotFound = 3954,
    GenerateLauncher_CopyError = 3961,
    GenerateLauncher_General = 3962,
    GenerateLauncher_InvalidInput = 3963,
    GenerateLauncher_MissingLauncherExe = 3964,
    GenerateLauncher_NoOutputPath = 3965,
    GetReferenceAssemblyPaths_OutOfDateSDK = 3971,
    GetCompatiblePlatform_NoCompatiblePlatformFound = 3981,
    GetCompatiblePlatform_NoPlatformsListed = 3982,
    GetCompatiblePlatform_InvalidLookupTableFormat = 3983,
    CombineTargetFrameworkInfoProperties_NotNullAndEmptyRootElementName = 3991,
    CombineTargetFrameworkInfoProperties_NotNullRootElementName = 3992,
    AddToWin32Manifest_InvalidValueInSupportedArchitectures = 4300,
    TaskFactoryNotSupportedFailure = 4801,
    TaskRequiresFrameworkFailure = 4803,
    CommonSdk_NonExistentProjectReference = 9008,
    CommonSdk_SpecifiedSeverityDoesNotExist = 9901,
    CommonSdk_Prefer32BitAndPreferNativeArm64Enabled = 9902,
    CommonSdk_NoWin32ManifestAndPreferNativeArm64Enabled = 9903,
    CommonSdk_PlatformIsAnyCPUAndPreferNativeArm64Enabled = 9904,

    /*
     * The Utilities message bucket is: MSB6001 - MSB6200
     *
     * Next message code should be MSB6013
     *
     * Some unused codes which can also be reused (because their messages were deleted, and UE hasn't indexed the codes yet):
     *     <none>
     *
     * Don't forget to update this comment after using a new code.
     */
    General_InvalidToolSwitch = 6001,
    ToolTask_CommandTooLong = 6002,
    ToolTask_CouldNotStartToolExecutable = 6003,
    ToolTask_ToolExecutableNotFound = 6004,
    ToolTask_ToolCommandFailed = 6006,
    ToolTask_InvalidEnvironmentParameter = 6007,
    Tracking_RebuildingDueToInvalidTLog = 6008,
    Tracking_RebuildingDueToInvalidTLogContents = 6009,
    PlatformManifest_MissingPlatformXml = 6010,
    ToolTask_ValidateParametersFailed = 6011,
    DebugPathTooLong = 6012,

    // Framework
    General_TwoVectorsMustHaveSameLength = 3094,
    General_InvalidPropertyError = 3100,
    MSBuild_ProjectFileNotFound = 3202,
    MSBuild_CannotRebaseOutputItemPath = 3203,
    MSBuild_ProjectUpgradeNeededToVcxProj = 3204,
    MSBuild_InvalidSkipNonexistentProjectValue = 3205,
    Message_InvalidImportance = 3511,
    ConflictingTaskAssembly = 4008,
    TaskNotMarshalByRef = 4077,
    UnrecognizedToolsVersion = 4132,
    KillingProcess = 5002,
    NameInvalid = 5016,
    FailedDeletingTempFile = 5018,
    KillingProcessByCancellation = 5021,
    WildcardResultsInDriveEnumeration = 5029,
    LoggingBeforeTaskInitialization = 6005,
}
